In [1]:
import numpy as np


In [42]:
#%%timeit
#Вводиться число n. Вивести масив разміра nхn, в якому по 
#діагоналі йдуть числа від 1 до n, а інші числа рівні 0
n=5
Z = np.diag(1+np.arange(n))
print(Z)


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [3]:
#%%timeit
n=5
Z = [ [ 0 for i in range(n) ] for j in range(n) ]
for i in range(0,n):
    for j in range(0,n):
        #Z[i,j]=0
        if(i==j):
            Z[i][j]=i+1
Z

[[1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0],
 [0, 0, 0, 0, 5]]

In [4]:
#%%timeit
#Вводяться 4 числа n, m, r, c. Вивести масив розміру n на m, в 
#якому в кожному r -му рядку і в кожному c-му стовпчику стоять 0, а інші 
#елементи дорівнюють 1.
n=6
m=7
r=2
c=3
Z=np.ones((n,m))
Z[0::r,:] = 0
Z[:,0::c] = 0
print(Z)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0.]]


In [5]:
#%%timeit
n=6
m=7
r=2
c=3
Z1 = [ [ 1 for i in range(m) ] for j in range(n) ]
for i in range(0,n,r):
    for j in range(0,m):
        Z1[i][j]=0
for i in range(0,n):
    for j in range(0,m,c):
        Z1[i][j]=0
Z1

[[0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 1, 0]]

In [6]:
#%%timeit
#З клавіатури вводиться масив. Замінити всі ненульові елементи на -1.
Z = np.array([3,4,0,9,7,0,6,0,4,0,3])
Z[Z != 0 ] = -1
print(Z)

[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]


In [7]:
#%%timeit
Z1 = [3,4,0,9,7,0,6,0,4,0,3]
for i in range(0,len(Z1)):
    if(Z1[i]!=0):
        Z1[i]=-1
Z1

[-1, -1, 0, -1, -1, 0, -1, 0, -1, 0, -1]

In [8]:
#З клавіатури вводиться масив. Замінити всі нульові елементи на -1.
Z = np.array([3,4,0,6,5,0,2,0,4])
Z[Z == 0 ] = -1
print(Z)
#//////////////////////////////////////
Z1 = [3,4,0,6,5,0,2,0,4]
for i in range(0,len(Z1)):
    if(Z1[i]==0):
        Z1[i]=-1
Z1

[ 3  4 -1  6  5 -1  2 -1  4]


[3, 4, -1, 6, 5, -1, 2, -1, 4]

In [9]:
#З клавіатури вводиться масив. Підрахувати в ньому кількість 
#нульових та ненульoвих елементів.
Z = np.array([3,4,0,9,8,2,4,0,8,4,0])
nz = np.count_nonzero(Z)
n = Z.size - nz
print("Нулей:",n)
print("Не нулей:",nz)
#//////////////////////////////////////
Z1 = [3,4,0,9,8,2,4,0,8,4,0]
count=0
for i in range(0,len(Z1)):
    if(Z1[i]==0):
        count+=1
print("Нулей:",count)
print("Не нулей:",len(Z1)-count)

Нулей: 3
Не нулей: 8
Нулей: 3
Не нулей: 8


In [11]:
#Створити масив одиниць розміром n х n та додати до нього 
#«рамку», сформовану з 0.
n=7
Z = np.ones((n,n))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)
#//////////////////////////////////////
Z1 = [ [ 1 for i in range(n) ] for j in range(n) ]
row_len = len(Z1)
col_len = len(Z1[0])
A = list()
for j in range(col_len+2):  # Adding two more rows
    if j == 0 or j == col_len + 1:
        A.append([0] * (row_len + 2))  # First and last row is just zeroes
    else:
        A.append([0] + Z1[j - 1] + [0])  # Append a zero to the front and back of each row
A

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


[[0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 1, 1, 1, 1, 1, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [12]:
#Заповнити вектор значеннями від 0 до n. Всі значення, що більші 
#за n/4 та менші за 3n/4 замінити нулями
n=10
Z = np.arange(n+1)
Z[(Z>n/4)&(Z<3*n/4)]=0
print(Z)
#//////////////////////////////////////
Z1 = [ i for i in range(n+1) ]
for i in range(n+1):
    if((Z1[i]>n/4) & (Z1[i]<3*n/4)):
        Z1[i]=0
Z1


[ 0  1  2  0  0  0  0  0  8  9 10]


[0, 1, 2, 0, 0, 0, 0, 0, 8, 9, 10]

In [16]:
#Згенерувати вектор з n випадкових чисел в діапазоні від 0 до 99. 
#Визначити кількість унікальних чисел в послідовності
n=8
Z = np.random.randint(15, size=n)
print("В последовательности: ",Z," - ",len(np.unique(Z)),"уникальных значений")
#//////////////////////////////////////
import random
low = 0
high = 15
cols = n
rows = 1
Z1 = [random.choices(range(low,high), k=cols) for _ in range(rows)]
Z2=Z1[0].copy()
Z2.sort()
Z3 = []
for i in range(0,(len(Z2))-1):
    if(Z2[i]!=Z2[i+1]):
        Z3.append(Z2[i])
Z3.append(Z2[n-1])

print("В последовательности: ",Z1[0]," - ",len(Z3),"уникальных значений")


В последовательности:  [ 1  6  6  7  0 11  6  4]  -  6 уникальных значений
В последовательности:  [12, 3, 1, 1, 2, 11, 3, 8]  -  6 уникальных значений


In [17]:
#Згенерувати вектор із n елементів, що рівномірно розміщені на 
#інтервалі (0,1) – тобто обидва кінці інтервалу не включені. Значення вивести 
#до 3 знаків після коми.
n=10
m=100//n
Z = np.linspace(0.0,1.0,n+1,endpoint = False)[1:]
Z=np.sort(Z)
print(np.round(Z,3))
#/////////////////////////////////////////////////
result = [x / 100 for x in range(1, 100, m)]
result

[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]


[0.01, 0.11, 0.21, 0.31, 0.41, 0.51, 0.61, 0.71, 0.81, 0.91]

In [19]:
%%latex
$$\begin{cases} x_1 + 2x_2 + 3x_3 + 4x_4 = 5 \\ 2x_1 + x_2 + 2x_3 + 3x_4 = 1 \\ 3x_1 + 2x_2 + x_3 + 2x_4 = 1 \\ 4x_1 + 3x_2 + 2x_3 + x_4 = -5 \end{cases} $$
$ Розв’язати \ систему \ за \ допомогою \ формул \ Крамера \ і \ виконати \ перевірку \ за \ допомогою:
 \\ a) \ матричного \ множення;
 \\ b) \ оберненої \ матриці; 
 \\c) \ функції \ numpy.linalg.solve().\\
Порівняти \ всі \ рішення \ за \ допомогою \ функції \ numpy.allclose()$

<IPython.core.display.Latex object>

In [20]:
#КРАМЕРА
from numpy import linalg
 
A=[[1, 2, 3, 4], [2, 1, 2, 3], [3, 2, 1,2], [4, 3, 2, 1]]
B=[5, 1, 1, -5]
C=[[1, 2, 3, 4], [2, 1, 2, 3], [3, 2, 1,2], [4, 3, 2, 1]]
X1=[]
for i in range(0,len(B)):
    for j in range(0,len(B)):
        C[j][i]=B[j]
        if i>0:
            C[j][i-1]=A[j][i-1]
    X1.append(round(linalg.det(C)/linalg.det(A),1))
 
print(X1)


[-2.0, 2.0, -3.0, 3.0]


In [35]:
#Перевірка за допомогою матричного перемноження
A=[[1, 2, 3, 4], [2, 1, 2, 3], [3, 2, 1,2], [4, 3, 2, 1]]

B=[5, 1, 1, -5]
X2 = np.dot(B,np.linalg.inv(A))
print(np.reshape(A,(4,4)))
print(np.reshape(B,(4,1)))
print(X2)

[[1 2 3 4]
 [2 1 2 3]
 [3 2 1 2]
 [4 3 2 1]]
[[ 5]
 [ 1]
 [ 1]
 [-5]]
[-2.  2. -3.  3.]


In [36]:
#Перевірка за допомогою функції numpy.linalg.solve()
Z = np.array([[1, 2, 3, 4], [2, 1, 2, 3], [3, 2, 1,2], [4, 3, 2, 1]])
b = np.array([5, 1, 1, -5])
X3 = np.linalg.solve(Z, b)
print(X3)

[-2.  2. -3.  3.]


In [37]:
np.allclose(X1,X2)

True

In [38]:
%%latex
$$Обчислити \ значення \ матричного \ виразу \
2(A-B)(A^2+B), \ де$$
$$A = 
\begin{pmatrix}
5 & 1 & 7 \\
-10 & -2 & 1 \\
0 & 1 & 2
\end{pmatrix}
B = 
\begin{pmatrix}
2 & 4 & 1 \\
3 & 1 & 0 \\
7 & 2 & 1
\end{pmatrix}$$


<IPython.core.display.Latex object>

In [39]:
#%%timeit
A = np.array([[5,1,7],[-10,-2,1],[0,1,2]])
B = np.array([[2,4,1],[3,1,0],[7,2,1]])
X=np.dot(2*(A-B),(np.dot(A,A)+B))
print(X)

[[ 228  132  798]
 [-286 -336 -894]
 [-190 -184 -562]]


In [40]:
#%%timeit
A = [[5,1,7],[-10,-2,1],[0,1,2]]
B = [[2,4,1],[3,1,0],[7,2,1]]
C = [ [ 1 for i in range(3) ] for j in range(3) ]
C2 = [ [ 0 for i in range(3) ] for j in range(3) ]
C3 = [ [ 0 for i in range(3) ] for j in range(3) ]
res = [ [ 0 for i in range(3) ] for j in range(3) ]
for i in range(0,3):
    for j in range(0,3):
        C[i][j] = 2*(A[i][j]-B[i][j])
for i in range(3):
    for j in range(3):
        for k in range(3):
            C2[i][j] += A[i][k] * A[k][j]
for i in range(0,3):
    for j in range(0,3):
        C3[i][j] = C2[i][j]+B[i][j]
for i in range(3):
    for j in range(3):
        for k in range(3):
            res[i][j] += C[i][k] * C3[k][j]
print(res)
np.allclose(X,res)

[[228, 132, 798], [-286, -336, -894], [-190, -184, -562]]


True